import type { Metadata } from 'next';
import '@/styles/globals.css';
import Header from '@/components/layouts/Header';

const baseTheme = 'base-dark-theme';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ko">
            <body className={baseTheme}>
                <Header />
                {children}
            </body>
        </html>
    );
}
