import type { Metadata } from 'next';
import '@/styles/globals.css';
import Header from '@/components/layouts/Header';
import MyLibrary from '@/components/layouts/MyLibrary';
import { cn } from '@/lib/utils';

const baseTheme = 'base-dark-theme';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ko">
            <body className={cn(baseTheme, 'overflow-hidden')}>
                <Header />
                <div className="flex gap-4">
                    <MyLibrary />
                    <main className="flex-1">
                        {children}
                    </main>
                </div>
            </body>
        </html>
    );
}
